config/routes.rb
Rails.application.routes.draw do

  # ユーザー新規登録、ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users', to: 'public/registrations#new'
  end

  # 管理者ログイン
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  scope module: :public do
    root to: 'homes#top'
    get 'search', to: 'searches#search'
    resources :users, only: %i[show update] do
      member do
        get 'edit_information', as: 'edit'
        patch 'withdrawal'
        get :likes
        get 'timeline'
      end
      resource :relations, only: %i[create destroy]
      get 'followings', to: 'relations#followings', as: 'followings'
      get 'followers', to: 'relations#followers', as: 'followers'
    end
    resources :posts do
      resource :likes, only: %i[create destroy]
      resources :comments, only: %i[create destroy] do
        resource :comment_likes, only: %i[create destroy]
      end
    end
    resources :tags, only: %i[show]
    resources :notifications, only: %i[index]
    resources :rooms, only: %i[index show create]
    resources :messages, only: %i[create]
    resources :room_groups do
      resources :message_groups, only: %i[create]
      resources :user_groups, only: %i[create index destroy]
    end
    resources :rates, only: %i[new create]
    resources :violates, only: %i[create]
  end

  # 管理者用
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[index show edit update]
    resources :posts, only: %i[index show destroy]
    resources :tags, only: %i[index show]
    resources :comments, only: %i[index destroy]
    resources :rates, only: %i[index]
    resources :violates, only: %i[index]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

  validates :text, presence: true

  scope :all_created_desc, -> {includes(:user, :post).all.order(created_at: :desc)}

  def comment_like(comment, current_user)
    comment_likes.where(comment_id: comment.id, user_id: current_user.id).empty?
  end

  def self.search_keyword_present(post_comments, keyword, model)
    return search_by_keyword_and_model(keyword, model) if keyword.present?
    load_for_posts(post_comments)
  end

  def self.search_by_keyword_and_model(keyword, model)
    if model == 'user'
      users = User.search_for(keyword)
      Comment.joins(:user).where(user_id: users.ids).order(created_at: :desc)
    else
      posts = Post.search_for(keyword)
      Comment.joins(:post).where(post_id: posts.ids).order(created_at: :desc)
    end
  end

  def self.load_for_posts(post_comments)
    if post_comments
      Comment.where(post_id: post_comments)
    else
      Comment.all_created_desc
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    post_comments = params[:post_comments]
    @keyword = params[:keyword]
    @model = params[:model]
    @comments = Comment.search_keyword_present(post_comments, @keyword, @model).page(params[:page]).per(10)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_comments_path, notice: 'コメントを削除しました'
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
  <h3 class="text-center">コメント一覧</h3>
  <div class="form-inline">
    <div class="mx-auto form-group mb-3">
      <%= form_with url: admin_comments_path, method: :get do |f| %>
        <%= f.text_field :keyword, placeholder: "検索内容", class:'form-control' %>
        <%= f.select :model, options_for_select({'ユーザー'=>'user', '投稿'=>'post'}), {prompt: false}, class:"pt-1 pb-2 rounded border border-secondary mr-2" %>
        <%= f.submit "検索", class:'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <%= render 'layouts/flash' %>
  <% if @comments.present? %>
    <table class="table table-bordered">
      <thead>
        <th class="col-1">コメントID</th>
        <th class="col-3">コメントしたユーザー</th>
        <th class="col-3">コメントされた投稿</th>
        <th class="col-4">コメント内容</th>
        <th class="col-1">削除</th>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.id %></td>
            <td>
              <%= link_to admin_user_path(comment.user) do %>
                <span class='border-bottom border-dark text-dark'>
                  <%= comment.user.name %>
                </span>
              <% end %>
            </td>
            <td>
              <%= link_to admin_post_path(comment.post) do %>
                <span class='border-bottom border-dark text-dark'>
                  <%= comment.post.post_name %>
                </span>
              <% end %>
            </td>
            <td><%= truncate(comment.text, length: 40, omission: "...") %></td>
            <td>
              <%= link_to '削除', admin_comment_path(comment.id), method: :delete, data: {confirm: "コメントを削除しますか？"}, class:'btn btn-outline-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <% if @keyword && @model == 'post' %>
      <h3 class="text-center">
        <%= @keyword %>の投稿に関連したコメントは見つかりませんでした。
      </h3>
    <% elsif %>
      <h3 class="text-center">
        <%= @keyword %>のユーザーに関連したコメントは見つかりませんでした。
      </h3>
    <% else %>
      <h3 class="text-center">コメントはありません</h3>
    <% end %>
  <% end %>
  <div class="row justify-content-center">
    <%= paginate @comments %>
  </div>
</div>