config/routes.rb
Rails.application.routes.draw do

  # ユーザー新規登録、ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users', to: 'public/registrations#new'
  end

  # 管理者ログイン
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  scope module: :public do
    root to: 'homes#top'
    get 'search', to: 'searches#search'
    resources :users, only: %i[show update] do
      member do
        get 'edit_information', as: 'edit'
        patch 'withdrawal'
        get :likes
        get 'timeline'
      end
      resource :relations, only: %i[create destroy]
      get 'followings', to: 'relations#followings', as: 'followings'
      get 'followers', to: 'relations#followers', as: 'followers'
    end
    resources :posts do
      resource :likes, only: %i[create destroy]
      resources :comments, only: %i[create destroy] do
        resource :comment_likes, only: %i[create destroy]
      end
    end
    resources :tags, only: %i[show]
    resources :notifications, only: %i[index]
    resources :rooms, only: %i[index show create]
    resources :messages, only: %i[create]
    resources :room_groups do
      resources :message_groups, only: %i[create]
      resources :user_groups, only: %i[create index destroy]
    end
    resources :rates, only: %i[new create]
    resources :violates, only: %i[create]
  end

  # 管理者用
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[index show edit update]
    resources :posts, only: %i[index show destroy]
    resources :tags, only: %i[index show]
    resources :comments, only: %i[index destroy]
    resources :rates, only: %i[index]
    resources :violates, only: %i[index]
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comment_likes, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  # グループチャットのアソシエーション
  has_many :user_groups, dependent: :destroy
  has_many :room_groups, dependent: :destroy
  has_many :message_groups, dependent: :destroy

  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  #フォローした、されたの関係
  has_many :relations, class_name: "Relation", foreign_key: "follow_id", dependent: :destroy
  has_many :reverse_relations, class_name: "Relation", foreign_key: "followed_id", dependent: :destroy
  has_many :followings_posts, through: :relations, source: :followed
  #class_name: "Relation"でRelationクラスの参照、foreign_key: カラム名で保存するカラムの指定

  #フォロー一覧
  has_many :followings, through: :relations, source: :followed       #フォロー中のユーザー一覧
  has_many :followers, through: :reverse_relations, source: :follow  #フォロワーのユーザー一覧

  # 通知機能のアソシエーション
  has_many :myself_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :other_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # サイトのレビューのアソシエーション
  has_many :rates, dependent: :destroy

  # ルール違反者を報告するアソシエーション
  has_many :reporter_violates, class_name: 'Violate', foreign_key: 'reporter_id', dependent: :destroy
  has_many :reported_violates, class_name: 'Violate', foreign_key: 'reported_id', dependent: :destroy

  # 管理者通知のアソシエーション
  has_many :admin_notifications, foreign_key: 'visitor_id', dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 100 }
  validates :encrypted_password, length: {minimum: 6}

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/profile_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: "#{width}x#{height}", gravity: "center", crop: "#{width}x#{height}+0+0").processed
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def follow?(user)
    followings.include?(user)
  end

  def written_by?(current_user, user)
    user == current_user
  end

  def self.search_keyword_present(keyword)
    return search_for(keyword) if keyword.present?
    all.order(created_at: :desc)
  end

  def self.search_for(keyword)
    User.where('name LIKE?', keyword+'%').order(created_at: :desc)
  end

  def create_notification_follow!(current_user)
    temp = Notification.find_by(
      ["visitor_id = ? and visited_id = ? and action = ?", current_user, id, 'follow']
    )
    if temp.blank?
      notification = current_user.myself_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 通知機能のチェックしていない通知のカウント
  def unchecked_notifications
    other_notifications.where(checked: false).count
  end

  def self.guest
    find_or_create_by(email: 'guest@sample.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.first_name = "ゲスト"
      user.last_name = "ユーザー"
      user.name = "ゲストユーザー"
      user.introduction = "こちらはゲストユーザーです。"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_users, except: %i[index]

  def index
    @keyword = params[:keyword]
    @users = User.search_keyword_present(@keyword)
    @search_path = admin_root_path
  end

  def show
    @user_posts = Post.where(user_id: @user.id)
  end

  def edit
    @image_url = url_for @user.profile_image
  end

  def update
    @image_url = url_for @user.profile_image
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
      flash[:notice] = "ユーザー情報を変更しました。"
    else
     render :edit
    end
  end

  private

  def set_users
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :name, :introduction, :email, :is_deleted, :profile_image)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    sign_in User.guest
    redirect_to user_path(current_user.id), notice: "ゲストユーザーとしてログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<!--管理者のユーザー情報編集画面-->
<div class="container">
  <h3 class="pb-3 text-center">
    <%= @user.name_in_database %>さん（ユーザーID：<%= @user.id %>）の会員情報編集画面
  </h3>
  <%= render 'layouts/error_messages', resource: @user %>
  <div class="col-12 col-lg-8 mx-auto">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <div class="form-group">
          <%= f.file_field :profile_image, accept: "image/*", onchange: "profileImage(this)" %>
          <div class="text-center">
            <%= image_tag @image_url, class:"m-2 profile_image border border-dark rounded-circle", id:"profile_image" %>
            <span id="preview"></span>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-6">
            <%= f.label :first_name, "苗字"%>
            <%= f.text_field :first_name, required: true, class:"form-control" %>
          </div>
          <div class="form-group col-6">
            <%= f.label :last_name, "名前"%>
            <%= f.text_field :last_name, required: true, class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, required: true, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :name, "ユーザー名" %>
          <%= f.text_field :name, required: true, class:"form-control" %>
          <div><span id="name_countUp"><%= @user.name&.length %></span>/20文字</div>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "ユーザーの説明" %>
          <%= f.text_area :introduction, class:"form-control" %>
          <div><span id="introduction_countUp"><%= @user.introduction&.length %></span>/100文字</div>
        </div>
        <div class="form-group">
          <%= f.label :is_deleted, "会員ステータス", class:"mr-3" %>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted_false, "有効", class:"text-success font-weight-bold mr-2" %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted_true, "退会", class:"text-danger font-weight-bold" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "編集する", class:"mb-3 btn btn-success" %>
        </div>
      <% end %>
    <div class="row justify-content-around">
      <%= link_to "会員一覧に戻る", admin_root_path, class:"btn btn-outline-info" %>
      <%= link_to "会員詳細に戻る", admin_user_path(@user), class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>

<script>
  function profileImage(obj){
    let fileReader;
    const preview = $('#preview');
    preview.empty();
  	fileReader = new FileReader();
  	fileReader.onload = (function (e) {
    	$('#profile_image').hide();
    	preview.html('<img class="m-2 border border-dark rounded-circle profile_image" src="' + e.target.result + '">');
  	});
  	fileReader.readAsDataURL(obj.files[0]);
  }
</script>

app/views/admin/users/index.html.erb
<!--管理者のユーザー一覧-->
<div class="container">
  <h3 class="text-center">会員一覧</h3>
  <%= render 'layouts/flash' %>
  <%= render 'admin/search/search_form', search_path: @search_path %>
  <% if @users.present? %>
    <table class="table table-bordered mx-auto">
      <thead>
        <th>会員ID</th>
        <th>ユーザー名</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>会員ステータス</th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <%= link_to admin_user_path(user.id) do %>
                <span class='border-bottom border-dark text-dark'>
                  <%= truncate(user.name, length: 15, omission: "...") %>
                </span>
              <% end %>
            </td>
            <td><%= user.full_name %></td>
            <td><%= truncate(user.email, length: 30, omission: "...") %></td>
            <td>
              <% if user.is_deleted == true %>
                <span class="text-danger font-weight-bold">退会済み</span>
              <% else %>
                <span class="text-success font-weight-bold">有効</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <% if @keyword %>
      <h3 class="text-center">
        <%= @keyword %>に関連したユーザーは見つかりませんでした
      </h3>
    <% else %>
      <h3 class="text-center">ユーザーはいません</h3>
    <% end %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<!--管理者のユーザーページ-->
<div class="container">
  <%= render 'layouts/flash' %>
  <div class="row pt-3">
    <div class="col-8 mx-auto">
      <div class="row">
        <div class="mx-auto">
          <div class="text-center mb-xs-0 mb-1">
            <%= image_tag @user.get_profile_image(150, 150), class:"border border-dark rounded-circle", width: 100, height: 100 %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <h4 class="pt-2">ユーザーID<span class="ml-3"><%= @user.id %></span></h4>
          <div class="border-bottom"></div>
          <h4 class="pt-2">ユーザー名</h4>
          <h5 class="ml-3"><%= @user.name %></h5>
          <div class="border-bottom"></div>
          <h4 class="pt-2">ユーザーの説明</h4>
          <h5 class="ml-3"><%= @user.introduction %></h5>
          <div class="border-bottom"></div>
          <h4 class="pt-2">フォロー中
            <span class="ml-3 pt-2"><%= @user.followings.count %>人</span>
          </h4>
          <h4 class="pt-2">フォロワー
            <span class="ml-3 pt-2"><%= @user.followers.count %>人</span>
          </h4>
          <div class="border-bottom"></div>
          <h4 class="pt-2">投稿数
            <span class="ml-3 pt-2"><%= @user_posts.count %>投稿</span>
          </h4>
          <h4>
            退会ステータス
            <% if @user.is_deleted %>
              <span class="text-danger">退会済み</span>
            <% else%>
              <span class="text-success">有効</span>
            <% end %>
          </h4>
          <div class="row justify-content-around pt-3">
            <%= link_to "会員一覧", admin_users_path, class:"btn btn-outline-primary" %>
            <%= link_to "編集", edit_admin_user_path(@user), class:"btn btn-outline-success" %>
            <% if @user_posts.present? %>
              <%= link_to "ユーザーの投稿一覧", admin_posts_path(user_id: @user.id), class:"btn btn-outline-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>