config/routes.rb
Rails.application.routes.draw do

  # ユーザー新規登録、ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users', to: 'public/registrations#new'
  end

  # 管理者ログイン
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  scope module: :public do
    root to: 'homes#top'
    get 'search', to: 'searches#search'
    resources :users, only: %i[show update] do
      member do
        get 'edit_information', as: 'edit'
        patch 'withdrawal'
        get :likes
        get 'timeline'
      end
      resource :relations, only: %i[create destroy]
      get 'followings', to: 'relations#followings', as: 'followings'
      get 'followers', to: 'relations#followers', as: 'followers'
    end
    resources :posts do
      resource :likes, only: %i[create destroy]
      resources :comments, only: %i[create destroy] do
        resource :comment_likes, only: %i[create destroy]
      end
    end
    resources :tags, only: %i[show]
    resources :notifications, only: %i[index]
    resources :rooms, only: %i[index show create]
    resources :messages, only: %i[create]
    resources :room_groups do
      resources :message_groups, only: %i[create]
      resources :user_groups, only: %i[create index destroy]
    end
    resources :rates, only: %i[new create]
    resources :violates, only: %i[create]
  end

  # 管理者用
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[index show edit update]
    resources :posts, only: %i[index show destroy]
    resources :tags, only: %i[index show]
    resources :comments, only: %i[index destroy]
    resources :rates, only: %i[index]
    resources :violates, only: %i[index]
  end
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="text-center text-danger pt-3 pb-1">
    <h4><%= resource.errors.count %>件のエラーが発生しました</h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <div class="row">
          <div class="col-lg-2"></div>
          <div class="col-12 col-lg-6 mx-auto">
            <div class="row justify-content-start">
              <li class="text-danger"><%= message %></li>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="text-center pt-3 pb-1">
    <div class="text-success">
      <%= flash[:notice] %>
    </div>
    <div class="text-danger">
      <%= flash[:alert] %>
    </div>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<!--検索は前方一致のみ-->
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword %>
  <%= f.select :model, options_for_select({"ユーザー"=>"user", "投稿"=>"post"})%>
  <%= f.submit '検索' %>
<% end %>

app/views/layouts/_search_user.html.erb
<div class="row m-auto" style="max-width:800px;">
  <!--TODO　style-->
  <table class="table table-hover">
    <tbody>
      <% users.each do |user| %>
        <% if current_user.nil? %>
          <tr onclick='window.location="<%= admin_user_path(user) %>"' role="link">
        <% else %>
          <tr onclick='window.location="<%= user_path(user) %>"' role="link">
        <% end %>
          <td class="col-1">
            <%= image_tag user.profile_image, size: "75x75", class:"rounded-circle border border-dark" %>
          </td>
          <td>
            <span class="h5"><%= user.name %></span><br>
            <%= user.introduction %><br>
            フォロー中<%= user.followings.count %>
            フォロワー<%= user.followers.count %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nature</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5960b679dc.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <div class="d-block d-lg-none bg-phone">
          <div class="col-auto text-center">
            <h3 class="text-center m-0 pt-3 pb-3 ml-5 mr-3 d-inline-block">MFTS</h3>
            <span id="toggleButton" data-toggle="collapse" data-target="#ToggleExternalContent" aria-controls="ToggleExternalContent"><i id="toggleIcon" class="fa-solid fa-magnifying-glass fa-lg float-right mt-4 p-2"></i></span>
            <div class="pos-f-t">
              <div class="collapse" id="ToggleExternalContent">
                <div class="bg-phone p-1">
                  <%= render 'public/searches/phone_search_form'%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light d-none d-lg-block" style="background-color: #e3f2fd;">
      <% else %>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <% end %>
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if user_signed_in? %>
                <li class="nav-item" >
                  <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to 'タイムライン', timeline_user_path(current_user), class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "投稿一覧", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "グループチャット", room_groups_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to '通知', notifications_path, class: 'nav-link text-dark' %>
                  <% if current_user.unchecked_notifications > 0 %>
                    <span class="fa-layers" style="position: relative;">
                      <span class="icon_layers_counter">+<%= current_user.unchecked_notifications %></span>
                    </span>
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item" >
                  <%= link_to "会員一覧", admin_root_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "コメント一覧", admin_comments_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to admin_rates_path, class: 'nav-link text-dark' do %>
                    <% if Rate.count_unchecked_notifications() == 0 %>
                      レビュー一覧
                    <% else %>
                      <p class="icon_layers">レビュー一覧</p>
                       <span class="n-circle">+<%= Rate.count_unchecked_notifications() %></span>
                    <% end %>
                  <% end %>
                </li>
                <li class="nav-item" >
                  <%= link_to admin_violates_path, class: 'nav-link text-dark' do %>
                    <% if Violate.count_unchecked_notifications() == 0 %>
                      違反通知
                    <% else %>
                      <p class="icon_layers">違反通知</p>
                       <span class="n-circle">+<%= Violate.count_unchecked_notifications() %></span>
                    <% end %>
                  <% end %>
                </li>
                <li class="nav-item" >
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              <% else %>
                <li class="nav-item" >
                  <%= link_to "Top", root_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "ゲストログイン", guest_sign_in_path, method: :post, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
            <div class="d-none d-lg-block">
              <%= render 'public/searches/form' if user_signed_in? %>
              <%= link_to "管理者ログイン", new_admin_session_path, class: 'text-dark' unless admin_signed_in? || user_signed_in? %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="border border-bottom d-none d-lg-block"></div>
    <div class="bg-light pb-5 pt-5 bg-height-color">
      <%= yield %>
    </div>
    <% if user_signed_in? %>
      <div class="pt-3 d-block d-lg-none"></div>
      <footer class="d-block d-lg-none pt-3 pb-3 mt-3 fixed-bottom bg-phone">
        <div class="col-10 mx-auto">
          <div class="row justify-content-around">
            <%= link_to user_path(current_user), class: 'text-dark' do %>
              <i class="fa-solid fa-user fa-xl"></i>
            <% end %>
            <%= link_to timeline_user_path(current_user), class: 'text-dark' do  %>
              <i class="fa-solid fa-house fa-xl"></i>
            <% end %>
            <%= link_to posts_path, class: 'text-dark' do %>
              <i class="fa-solid fa-images fa-xl"></i>
            <% end %>
            <%= link_to notifications_path, class: 'text-dark' do %>
              <i class="fa-solid fa-bell fa-xl"></i>
              <% if current_user.unchecked_notifications > 0 %>
                <span class="fa-layers" style="position: relative;">
                  <span class="phone_icon_layers_counter">+<%= current_user.unchecked_notifications %></span>
                </span>
              <% end %>
            <% end %>
            <%= link_to room_groups_path, class: 'text-dark' do %>
              <i class="fa-solid fa-users fa-xl"></i>
            <% end %>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>

<script>
  $(document).ready(function() {
    $("#toggleButton").click(function() {
      var icon = $("#toggleIcon");
      if (icon.hasClass("fa-solid fa-magnifying-glass fa-lg")) {
        icon.removeClass("fa-solid fa-magnifying-glass fa-lg").addClass("fa-solid fa-magnifying-glass-arrow-right fa-lg");
      } else {
        icon.removeClass("fa-solid fa-magnifying-glass-arrow-right fa-lg").addClass("fa-solid fa-magnifying-glass fa-lg");
      }
    });
  });
</script>

<!--FIXME: 改良できるかも, MEMO: メモ, TODO: 今後の予定, REF: 参考資料 ctrl+shift+f-->